# Generated by Django 5.2.3 on 2025-07-03 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensennanza', '0001_initial'),
        ('preguntas', '0002_pregunta_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='IA',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='corecta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subirimg',
            name='IA',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subirimg',
            name='IAPrompt',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subirimg',
            name='temaCorespondiente',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ensennanza.tema'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='texto',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
