# Generated by Django 5.2.3 on 2025-07-03 13:31

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0004_remove_pregunta_corecta_remove_subirimg_ia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='texto',
            field=markdownx.models.MarkdownxField(default=''),
            preserve_default=False,
        ),
    ]
