# Generated by Django 5.2.3 on 2025-07-16 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensennanza', '0001_initial'),
        ('preguntas', '0005_alter_pregunta_texto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('realizada', models.BooleanField(default=False)),
                ('calificacion', models.FloatField(default=0.0)),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('temas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ensennanza.tema')),
            ],
        ),
    ]
