# Generated by Django 5.2.3 on 2025-07-28 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0006_prueba'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prueba',
            old_name='temas',
            new_name='tema',
        ),
    ]
