# Generated by Django 5.2.3 on 2025-07-29 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0007_rename_temas_prueba_tema'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregunta',
            old_name='IA',
            new_name='ia',
        ),
        migrations.RenameField(
            model_name='respuesta',
            old_name='IA',
            new_name='ia',
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='titulo',
        ),
    ]
