# Generated by Django 5.2.3 on 2025-07-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0008_rename_ia_pregunta_ia_rename_ia_respuesta_ia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prueba',
            name='repetible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='IAPrompt',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
