# Generated by Django 5.2.3 on 2025-08-01 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0009_prueba_repetible_alter_pregunta_iaprompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='prueba',
            name='dificultad',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
    ]
