# Generated by Django 5.2.3 on 2025-08-01 15:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0010_prueba_dificultad'),
    ]

    operations = [
        migrations.AddField(
            model_name='prueba',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
