# Generated by Django 5.2.3 on 2025-06-29 21:57

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('dificultadMinima', models.IntegerField()),
                ('dificultadMaxima', models.IntegerField()),
                ('contenido', markdownx.models.MarkdownxField()),
            ],
        ),
    ]
