# Generated by Django 5.2.3 on 2025-07-29 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensennanza', '0001_initial'),
        ('inicioSesion', '0002_alter_usuario_tipo_usuario_curso_usuario_curso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tema',
            options={'ordering': ['orden']},
        ),
        migrations.RemoveField(
            model_name='tema',
            name='dificultadMaxima',
        ),
        migrations.RemoveField(
            model_name='tema',
            name='dificultadMinima',
        ),
        migrations.AddField(
            model_name='tema',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inicioSesion.curso'),
        ),
        migrations.AddField(
            model_name='tema',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
