# Generated by Django 5.2.3 on 2025-07-29 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensennanza', '0002_alter_tema_options_remove_tema_dificultadmaxima_and_more'),
        ('inicioSesion', '0002_alter_usuario_tipo_usuario_curso_usuario_curso'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tema',
            unique_together={('curso', 'orden')},
        ),
    ]
