# Generated by Django 5.2.3 on 2025-07-29 14:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicioSesion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('alumno', 'Alumno'), ('profesor', 'Profesor'), ('administrador', 'Administrador')], default='alumno', max_length=20),
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCurso', models.CharField(max_length=70)),
                ('dificultadMinima', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('dificultadMaxima', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('profesor', models.ForeignKey(limit_choices_to={'tipo_usuario': 'profesor'}, on_delete=django.db.models.deletion.PROTECT, related_name='cursos_dictados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='Curso',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos', to='inicioSesion.curso'),
        ),
    ]
