# Generated by Django 5.2.3 on 2025-08-01 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensennanza', '0004_curso_alter_tema_curso'),
        ('inicioSesion', '0002_alter_usuario_tipo_usuario_curso_usuario_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Curso',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos', to='ensennanza.curso'),
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
