# Generated by Django 5.2.3 on 2025-08-01 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicioSesion', '0003_alter_usuario_curso_delete_curso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='Curso',
            new_name='curso',
        ),
    ]
