# Generated by Django 5.2.3 on 2025-07-28 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0001_initial'),
        ('preguntas', '0007_rename_temas_prueba_tema'),
    ]

    operations = [
        migrations.CreateModel(
            name='emociones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emociones', models.JSONField()),
                ('emocionPredominante', models.CharField(max_length=50)),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preguntas.prueba')),
            ],
        ),
    ]
