# Generated by Django 5.2.3 on 2025-08-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0002_emociones'),
    ]

    operations = [
        migrations.AddField(
            model_name='emociones',
            name='numImgProsesadas',
            field=models.IntegerField(default=0),
        ),
    ]
