# Generated by Django 5.2.3 on 2025-08-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0003_emociones_numimgprosesadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emociones',
            name='emocionPredominante',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
